name: Terraform CI

on:
  push:
    branches: [ main ]
    paths:
      - 'Bootstrap/backend-bucket/**'
      - 'Bootstrap/oidc/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    paths:
      - 'Bootstrap/backend-bucket/**'
      - 'Bootstrap/oidc/**'
      - '.github/workflows/terraform.yml' 
  
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::061039787667:role/github-actions-oidc-role
          aws-region: eu-west-2
      
      - name: Terraform Init
        working-directory: Bootstrap/backend-bucket
        run: terraform init

      - name: Terraform Validate
        working-directory: Bootstrap/backend-bucket
        run: terraform validate

      - name: Terraform Plan
        working-directory: Bootstrap/backend-bucket
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: Bootstrap/backend-bucket
        run: terraform apply -auto-approve


      - name: Terraform Init
        working-directory: Bootstrap/oidc
        run: terraform init

      - name: Terraform Validate
        working-directory: Bootstrap/oidc
        run: terraform validate

      - name: Terraform Plan
        working-directory: Bootstrap/oidc
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: Bootstrap/oidc
        run: terraform apply -auto-approve 